### ISSUE TITLE
ImportError: dlopen(_UnsymmetricPairAlignment.so, 2): no suitable image found.

### ISSUE THREAD

**Issue by bnbowman** [WGLab/RepeatHMM#4]
Unable to get repeatHMM to run on Mac, but I'm unsure of the cause - I've never tried to interface between Python and an Shared Object file before

```
Traceback (most recent call last):
  File "bin/repeatHMM.py", line 17, in <module>
    from scripts import myBAMhandler #
  File "/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/myBAMhandler.py", line 23, in <module>
    import getAlignment
  File "/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/getAlignment.py", line 7, in <module>
    from UnsymmetricPairAlignment import UnsymmetricPairAlignment; 
  File "/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/UnsymmetricPairAlignment/UnsymmetricPairAlignment.py", line 28, in <module>
    _UnsymmetricPairAlignment = swig_import_helper()
  File "/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/UnsymmetricPairAlignment/UnsymmetricPairAlignment.py", line 24, in swig_import_helper
    _mod = imp.load_module('_UnsymmetricPairAlignment', fp, pathname, description)
ImportError: dlopen(/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/UnsymmetricPairAlignment/_UnsymmetricPairAlignment.so, 2): no suitable image found.  Did find:
	/Users/bbowman/2017/9/Rpt_RepeatHMM/RepeatHMM/bin/scripts/UnsymmetricPairAlignment/_UnsymmetricPairAlignment.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by liuqianhn** [comment]
Hi, could you please to go "bin/scripts/UnsymmetricPairAlignment/", and remove "_UnsymmetricPairAlignment.so", and then "make"? Please let me know what is the ouput/error. Thanks.

**Comment by bnbowman** [comment]
That worked.  Thanks!

-Brett

**Comment by liuqianhn** [comment]
Hi Brett,

Glad it worked. Please also update RepeatHMM since I fixed issues. Thanks for being interested in RepeatHMM. Please let me know if there is any issue.



On Sep 13, 2017, at 12:08 AM, Brett Bowman (@BioInfoBrett) <notifications@github.com<mailto:notifications@github.com>> wrote:

That worked. Thanks!

-Brett
