### ISSUE TITLE
Multi-thread errors

### ISSUE THREAD

**Issue by woodoo46** [WGLab/RepeatHMM#42]
Hi,

When I ran repeatHMM with multi-threaded mode, for example with option --thread 8. I had this error

lib/python2.7/site-packages/RepeatHMM-2.0-py2.7-linux-x86_64.egg/RepeatHMM_scripts/myScanWholeGenome.py", line 466, in scan_part
    ti, mi, chrk = curPartition[-1]
ValueError: too many values to unpack

This is my command:
${repeatHMM} Scan --SplitAndReAlign 1 --MinSup 3 --UserDefinedUniqID chr10.0000.scan --SeqTech Pacbio --Patternfile ${patternfile} --Onebamfile ${bamfile} --hgfile ${genome} --thread 8 --cluster 0

If I do not set --thread, the program went through.

Thanks!.

George

**Comment by liuqianhn** [comment]
@woodoo46 Thanks for reporting this issue and for being interested in scan module. I will check it and fix the issue.

**Comment by LiShuhang-gif** [comment]
Hi, have you already fix this issue? I have encountered the same "ValueError" when using multiple threads.

**Comment by shaohua-fan** [comment]
@liuqianhn we met the same problem when using the scan module with multi-thread mode.

We used 

repeatHMM.py Scan --SplitAndReAlign 1 --MinSup 3 --UserDefinedUniqID WGSscan --SeqTech "Nanopore" "--Patternfile" hg38.trf.bed --cluster 0 --envset repeathmmenv  --Onebamfile minimap2_sorted_rmdup_p20.bam --hgfile hg38_22_XYM.fa --thread 10

We observed the followings error messages:

 Process Process-1:
Traceback (most recent call last):
  File "/public/home/yes/envs/repeathmmenv/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/public/home/yes/envs/repeathmmenv/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/public/home/repeatHMM/RepeatHMM/bin/RepeatHMM_scripts/myScanWholeGenome.py", line 466, in scan_part
    ti, mi, chrk = curPartition[-1]
ValueError: too many values to unpack

Can you please let us know how to fix this problem?

**Comment by genkiguan** [comment]
@liuqianhn Hi, I also met the same problem when using multi-thread. Could you please help me figure it out?

**Comment by quantrannnn** [comment]
@liuqianhn Hi, I met the same error when running repeatHMM Scan in multi-thread mode. I only can run with --thread 1 but it took too much time. Could you help me with this problem? Thanks
