### ISSUE TITLE
error in RepeatHMM Scan

### ISSUE THREAD

**Issue by stat-lab** [WGLab/RepeatHMM#48]
An error occurred when repeatHMM.py Scan was executed, but the process has continued and not yet ended for 1 week.
The repeat bed file provided was obtained from the UCSC genome browser. This run was restricted to only chr1. Does this error affect the result? Also, when does this run finish? My command and error messages are as follows:

repeatHMM.py Scan --region 1 --SplitAndReAlign 1 --MinSup 3 --max_len 5000 --Onebamfile NA12878_nanopore_30x.minimap2.24.bam --envset repeathmmenv --avergnum 1000 --hg hg19 --hgfile ~/Ref/hs37d5.fa --Patternfile ~/Ref/hg19.trf.bed --repeathmmPath ~/tools/RepeatHMM-2.0.3/bin --UserDefinedUniqID NA12878_ONT_chr1 --SeqTech Nanopore --RepeatTime 2 --thread 12

[INFO/Process-1] child process calling self.run()
[INFO/Process-1] process shutting down
[DEBUG/Process-1] running all "atexit" finalizers with priority >= 0
[DEBUG/Process-1] running the remaining "atexit" finalizers
Process Process-1:
Traceback (most recent call last):
  File "/opt/local/python/2.7.12/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/local/python/2.7.12/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/share/project/sg/kosugi/tools/RepeatHMM-2.0.3/bin/RepeatHMM_scripts/myScanWholeGenome.py", line 466, in scan_part
    ti, mi, chrk = curPartition[-1]
ValueError: too many values to unpack
[INFO/Process-1] process exiting with exitcode 1
.
.
.

('firsthalf_analysis_file_id', 'gmm_GapCorrection1_FlankLength30_SplitAndReAlign1_2_7_4_80_10_100_hg19_comp_NA12878_ONT')
('secondhalf_analysis_file_id', '_Nanopore_I0.120_D0.020_S0.020.txt')
('maxind', {})
Average microsatellites per thread: 2008(1000)=24097/12
('split taks done', 24)
('jobs', 12, 12, 'times:', 0, -1, '2022/05/04 09:10:53')
('jobs', 12, 12, 'times:', 0, -1, '2022/05/04 09:27:34')
('jobs', 12, 12, 'times:', 0, -1, '2022/05/04 09:44:15')
.
.
.

**Comment by Lionward** [comment]
hey did you manage to solve this problem? I am facing the same error when allowing multiple threads

**Comment by stat-lab** [comment]
When I changed the reference based on the input bam to GRCh38 (--hg hg38) and the number of thread to 1 (--thread 1), the job was completed without errors.
