### ISSUE TITLE
An error in RepeatHMM Scan (using hg38.trf.nochr.bed)

### ISSUE THREAD

**Issue by fjmuzengyiheng** [WGLab/RepeatHMM#50]
Hi, an  error occured when I attempted to Scan genome-wide STR for Pacbio CCS reads.

Here is my command:

repeathmm_simg=/genetics/home/zengyiheng/project/zyh-pipeline/repeat/repeatHMM_v2.0.3.sigm
map_ref=/genetics/home/zengyiheng/project/zyh-pipeline/reference/grch38/GRCh38_alignment.fa
sample=jyl

singularity exec -B /genetics/:/genetics/ ${repeathmm_simg} python /app/v2.0.3/RepeatHMM/bin/repeatHMM.py Scan \
--SplitAndReAlign 0 \ 
--MinSup 3 \ 
--UserDefinedUniqID ${sample} \
--SeqTech "Pacbio" \
--Patternfile /genetics/home/zengyiheng/project/zyh-pipeline/repeathmm/hg38.trf.nochr.bed \
--Onebamfile /genetics/home/zengyiheng/project/7_lrs/pb/19620_jiyulan_ccs/bam_final/${sample}.hg38.sorted.bam \
--hgfile ${map_ref} \
--outFolder ${work_dir}/str

The error output is shown below:

**('Total size', 376966)
Traceback (most recent call last):
  File "/app/v2.0.3/RepeatHMM/bin/repeatHMM.py", line 713, in <module>
    args.func(args)
  File "/app/v2.0.3/RepeatHMM/bin/repeatHMM.py", line 400, in scan
    myScanWholeGenome.scan(commonOptions, specifiedOptions)
  File "/app/v2.0.3/RepeatHMM/bin/RepeatHMM_scripts/myScanWholeGenome.py", line 564, in scan
    detectRepCounts(commonOptions, specifiedOptions, moreOptions);
  File "/app/v2.0.3/RepeatHMM/bin/RepeatHMM_scripts/myScanWholeGenome.py", line 627, in detectRepCounts
    p2bamhmm = myBAMhandler.getRepeatForGivenGene(commonOptions, specifiedOptions, moreOptions)
  File "/app/v2.0.3/RepeatHMM/bin/RepeatHMM_scripts/myBAMhandler.py", line 471, in getRepeatForGivenGene
    queryrep = queryrep + aainfo[queryind - 1]
IndexError: string index out of range**

The bam input for RepeatHMM was generated using minimap2.

I can't figure out what caused this error. Is there any advice you can give me? Thank you so much.

Best wishes,
Yi-Heng Zeng

**Comment by liuqianhn** [comment]
Hi @fjmuzengyiheng could you please add `if queryind - 1>=len(aainfo): print("test471: '{}'".format(line))` before the line 471 and share what output you will get?
