### ISSUE TITLE
ImportError: cannot import name _UnsymmetricPairAlignment

### ISSUE THREAD

**Issue by aishsk87** [WGLab/RepeatHMM#55]
I have following versions of  Python 2 and 3 respectively,
Python 2.7.18 :: Anaconda, Inc.
Python 3.8.10
and I ran the steps as per the installation instructions, however I still the following error 
 
python RepeatHMM/bin/repeatHMM.py FASTQinput --repeatName atxn3 --GapCorrection 1 --FlankLength 30 --UserDefinedUniqID sca3_pcr25_raw_test --fastq SRR5363632.fastq --outFolder logfq --Patternfile RepeatHMM/bin/reference_sts/hg38/hg38.predefined.pa --hgfile hg38/hg38.fa --hg hg38
Traceback (most recent call last):
  File "RepeatHMM/bin/repeatHMM.py", line 18, in <module>
    from RepeatHMM_scripts import myBAMhandler
  File "/tools/RepeatHMM/bin/RepeatHMM_scripts/myBAMhandler.py", line 24, in <module>
    from . import getAlignment
  File "/tools/RepeatHMM/bin/RepeatHMM_scripts/getAlignment.py", line 7, in <module>
    from UnsymmetricPairAlignment import UnsymmetricPairAlignment
  File "/tools/RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment/UnsymmetricPairAlignment.py", line 13, in <module>
    from . import _UnsymmetricPairAlignment
ImportError: cannot import name _UnsymmetricPairAlignment

Any help will be extremely appreciated

**Comment by liuqianhn** [comment]
@aishsk87 could you please check #32 to see whether that solution works for you.

**Comment by aishsk87** [comment]
I did follow all the issues and followed the steps:

git clone https://github.com/WGLab/RepeatHMM.gitCloning into 'RepeatHMM'...
remote: Enumerating objects: 911, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 911 (delta 1), reused 3 (delta 1), pack-reused 903
Receiving objects: 100% (911/911), 901.78 KiB | 9.11 MiB/s, done.
Resolving deltas: 100% (503/503), done.


source activate repeathmmenv

cd RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment

make
swig -python UnsymmetricPairAlignment.i
python setup.py build_ext --inplace
running build_ext
building '_UnsymmetricPairAlignment' extension
creating build
creating build/temp.linux-x86_64-3.8
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c UnsymmetricPairAlignment_wrap.c -o build/temp.linux-x86_64-3.8/UnsymmetricPairAlignment_wrap.o
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c UnsymmetricPairAlignment.c -o build/temp.linux-x86_64-3.8/UnsymmetricPairAlignment.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/UnsymmetricPairAlignment_wrap.o build/temp.linux-x86_64-3.8/UnsymmetricPairAlignment.o -o /tools/RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment/_UnsymmetricPairAlignment.cpython-38-x86_64-linux-gnu.so

This is the content in UnsymmetricPairAlignment directory
RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment
build                       _UnsymmetricPairAlignment.cpython-38-x86_64-linux-gnu.so
__init__.py                 UnsymmetricPairAlignment.i
Makefile                    UnsymmetricPairAlignment.py
setup.py                    UnsymmetricPairAlignment_wrap.c
UnsymmetricPairAlignment.c

/RepeatHMM/bin/RepeatHMM_scripts/UnsymmetricPairAlignment/build/temp.linux-x86_64-3.8
UnsymmetricPairAlignment.o  UnsymmetricPairAlignment_wrap.o

I then ran the script as follows and this is what I get:

python RepeatHMM/bin/repeatHMM.py FASTQinput --repeatName atxn3 --GapCorrection 1 --FlankLength 30 --UserDefinedUniqID sca3_pcr25_raw_test --fastq SRR5363632.fastq --outFolder logfq --Patternfile RepeatHMM/bin/reference_sts/hg38/hg38.predefined.pa --hgfile hg38/hg38.fa --hg hg38
Traceback (most recent call last):
  File "RepeatHMM/bin/repeatHMM.py", line 18, in <module>
    from RepeatHMM_scripts import myBAMhandler
  File "/tools/RepeatHMM/bin/RepeatHMM_scripts/myBAMhandler.py", line 24, in <module>
    from . import getAlignment
  File "/tools/RepeatHMM/bin/RepeatHMM_scripts/getAlignment.py", line 7, in <module>
    from UnsymmetricPairAlignment import UnsymmetricPairAlignment
ModuleNotFoundError: No module named 'UnsymmetricPairAlignment'
